export const baseViewCardData = [
    {
        key: 'department',
        value: 846,
    },

    {
        key: 'catalog',
        value: 8846,
        detail: [
            {
                // 已理解
                key: 'understood',
                value: 122,
            },
            {
                // 未理解
                key: 'not_understood',
                value: 122,
            },
            {
                // 完成率
                key: 'completion_rate',
                value: 90,
            },
        ],
    },
    {
        key: 'task',
        detail: [
            {
                key: 'total',
                value: 846,
            },
            {
                // 已完成
                key: 'completed',
                value: 846,
            },
            {
                // 进行中
                key: 'in_progress',
                value: 846,
            },
            {
                // 异常
                key: 'abnormal',
                value: 846,
            },
        ],
    },
]

// 服务领域
export const serviceAreaDataMock = [
    {
        domain_name: 'data_catalog',
        credit_information: 0,
        financial_information: 0,
        healthcare_information: 0,
        city_traffic_information: 0,
        cultural_tourism_information: 0,
        administrative_law_enforcement_information: 0,
        party_building_information: 0,
    },
    {
        domain_name: 'table',
        credit_information: 1234,
        financial_information: 1234,
        healthcare_information: 1234,
        city_traffic_information: 0,
        cultural_tourism_information: 1234,
        administrative_law_enforcement_information: 1234,
        party_building_information: 1234,
    },
    {
        domain_name: 'business_object',
        credit_information: 1234,
        financial_information: 1234,
        healthcare_information: 1234,
        city_traffic_information: 1234,
        cultural_tourism_information: 1234,
        administrative_law_enforcement_information: 1234,
        party_building_information: 1234,
    },
]

// 基础信息分类
export const baseInfoClassificationDataMock = [
    {
        // 数据理解部门
        key: 'department',
        value: 1234,
    },
    {
        // 已理解数据目录
        key: 'understood_data_catalog',
        value: 1234,
    },
    {
        // 未理解数据目录
        key: 'not_understood_data_catalog',
        value: 1234,
    },
    {
        // 完成率
        key: 'completion_rate',
        value: 46,
    },
]

export const baseInfoClassificationTableDataMock = [
    {
        department_name: '部门1',
        understood_data_catalog_count: 1234,
        not_understood_data_catalog_count: 123,
        completion_rate: 46,
    },
    {
        department_name: '部门2',
        understood_data_catalog_count: 1100,
        not_understood_data_catalog_count: 220,
        completion_rate: 83,
    },
    {
        department_name: '部门3',
        understood_data_catalog_count: 980,
        not_understood_data_catalog_count: 340,
        completion_rate: 74,
    },
    {
        department_name: '部门4',
        understood_data_catalog_count: 870,
        not_understood_data_catalog_count: 430,
        completion_rate: 67,
    },
    {
        department_name: '部门5',
        understood_data_catalog_count: 760,
        not_understood_data_catalog_count: 540,
        completion_rate: 58,
    },
    {
        department_name: '部门6',
        understood_data_catalog_count: 650,
        not_understood_data_catalog_count: 600,
        completion_rate: 52,
    },
    {
        department_name: '部门7',
        understood_data_catalog_count: 540,
        not_understood_data_catalog_count: 660,
        completion_rate: 45,
    },
    {
        department_name: '部门8',
        understood_data_catalog_count: 430,
        not_understood_data_catalog_count: 720,
        completion_rate: 37,
    },
    {
        department_name: '部门9',
        understood_data_catalog_count: 320,
        not_understood_data_catalog_count: 780,
        completion_rate: 29,
    },
    {
        department_name: '部门10',
        understood_data_catalog_count: 210,
        not_understood_data_catalog_count: 840,
        completion_rate: 20,
    },
    {
        department_name: '部门11',
        understood_data_catalog_count: 1500,
        not_understood_data_catalog_count: 100,
        completion_rate: 94,
    },
    {
        department_name: '部门12',
        understood_data_catalog_count: 1400,
        not_understood_data_catalog_count: 120,
        completion_rate: 92,
    },
    {
        department_name: '部门13',
        understood_data_catalog_count: 1300,
        not_understood_data_catalog_count: 140,
        completion_rate: 90,
    },
    {
        department_name: '部门14',
        understood_data_catalog_count: 1200,
        not_understood_data_catalog_count: 160,
        completion_rate: 88,
    },
    {
        department_name: '部门15',
        understood_data_catalog_count: 1100,
        not_understood_data_catalog_count: 180,
        completion_rate: 86,
    },
    {
        department_name: '部门16',
        understood_data_catalog_count: 1000,
        not_understood_data_catalog_count: 200,
        completion_rate: 83,
    },
    {
        department_name: '部门17',
        understood_data_catalog_count: 900,
        not_understood_data_catalog_count: 220,
        completion_rate: 80,
    },
    {
        department_name: '部门18',
        understood_data_catalog_count: 800,
        not_understood_data_catalog_count: 240,
        completion_rate: 77,
    },
    {
        department_name: '部门19',
        understood_data_catalog_count: 700,
        not_understood_data_catalog_count: 260,
        completion_rate: 73,
    },
    {
        department_name: '部门20',
        understood_data_catalog_count: 600,
        not_understood_data_catalog_count: 280,
        completion_rate: 68,
    },
    {
        department_name: '部门21',
        understood_data_catalog_count: 500,
        not_understood_data_catalog_count: 300,
        completion_rate: 62,
    },
    {
        department_name: '部门22',
        understood_data_catalog_count: 450,
        not_understood_data_catalog_count: 320,
        completion_rate: 58,
    },
    {
        department_name: '部门23',
        understood_data_catalog_count: 400,
        not_understood_data_catalog_count: 340,
        completion_rate: 54,
    },
    {
        department_name: '部门24',
        understood_data_catalog_count: 350,
        not_understood_data_catalog_count: 360,
        completion_rate: 49,
    },
    {
        department_name: '部门25',
        understood_data_catalog_count: 300,
        not_understood_data_catalog_count: 380,
        completion_rate: 44,
    },
    {
        department_name: '部门26',
        understood_data_catalog_count: 260,
        not_understood_data_catalog_count: 400,
        completion_rate: 39,
    },
    {
        department_name: '部门27',
        understood_data_catalog_count: 220,
        not_understood_data_catalog_count: 420,
        completion_rate: 34,
    },
    {
        department_name: '部门28',
        understood_data_catalog_count: 180,
        not_understood_data_catalog_count: 440,
        completion_rate: 29,
    },
    {
        department_name: '部门29',
        understood_data_catalog_count: 140,
        not_understood_data_catalog_count: 460,
        completion_rate: 23,
    },
    {
        department_name: '部门30',
        understood_data_catalog_count: 100,
        not_understood_data_catalog_count: 480,
        completion_rate: 17,
    },
]

// ... existing code ...

export const understandDepartmentDetailDataMock = [
    {
        department_name: '技术研发部',
        understood_data_catalog_count: 1856,
        not_understood_data_catalog_count: 234,
        completion_rate: 89,
    },
    {
        department_name: '数据管理部',
        understood_data_catalog_count: 1642,
        not_understood_data_catalog_count: 158,
        completion_rate: 91,
    },
    {
        department_name: '业务分析部',
        understood_data_catalog_count: 1428,
        not_understood_data_catalog_count: 372,
        completion_rate: 79,
    },
    {
        department_name: '运营支持部',
        understood_data_catalog_count: 1205,
        not_understood_data_catalog_count: 495,
        completion_rate: 71,
    },
    {
        department_name: '质量保障部',
        understood_data_catalog_count: 987,
        not_understood_data_catalog_count: 613,
        completion_rate: 62,
    },
    {
        department_name: '客户服务部',
        understood_data_catalog_count: 876,
        not_understood_data_catalog_count: 624,
        completion_rate: 58,
    },
    {
        department_name: '市场营销部',
        understood_data_catalog_count: 765,
        not_understood_data_catalog_count: 735,
        completion_rate: 51,
    },
    {
        department_name: '人力资源部',
        understood_data_catalog_count: 654,
        not_understood_data_catalog_count: 846,
        completion_rate: 44,
    },
    {
        department_name: '财务审计部',
        understood_data_catalog_count: 543,
        not_understood_data_catalog_count: 957,
        completion_rate: 36,
    },
    {
        department_name: '法务合规部',
        understood_data_catalog_count: 432,
        not_understood_data_catalog_count: 1068,
        completion_rate: 29,
    },
    {
        department_name: '信息安全部',
        understood_data_catalog_count: 321,
        not_understood_data_catalog_count: 1179,
        completion_rate: 21,
    },
    {
        department_name: '产品设计部',
        understood_data_catalog_count: 210,
        not_understood_data_catalog_count: 1290,
        completion_rate: 14,
    },
    {
        department_name: '系统集成部',
        understood_data_catalog_count: 1987,
        not_understood_data_catalog_count: 113,
        completion_rate: 95,
    },
    {
        department_name: '云计算部',
        understood_data_catalog_count: 1754,
        not_understood_data_catalog_count: 146,
        completion_rate: 92,
    },
    {
        department_name: '人工智能部',
        understood_data_catalog_count: 1632,
        not_understood_data_catalog_count: 168,
        completion_rate: 91,
    },
    {
        department_name: '区块链技术部',
        understood_data_catalog_count: 1521,
        not_understood_data_catalog_count: 179,
        completion_rate: 89,
    },
    {
        department_name: '物联网部',
        understood_data_catalog_count: 1409,
        not_understood_data_catalog_count: 191,
        completion_rate: 88,
    },
    {
        department_name: '移动开发部',
        understood_data_catalog_count: 1298,
        not_understood_data_catalog_count: 202,
        completion_rate: 87,
    },
    {
        department_name: '前端开发部',
        understood_data_catalog_count: 1187,
        not_understood_data_catalog_count: 213,
        completion_rate: 85,
    },
    {
        department_name: '后端开发部',
        understood_data_catalog_count: 1076,
        not_understood_data_catalog_count: 224,
        completion_rate: 83,
    },
    {
        department_name: '测试工程部',
        understood_data_catalog_count: 965,
        not_understood_data_catalog_count: 235,
        completion_rate: 80,
    },
    {
        department_name: '运维保障部',
        understood_data_catalog_count: 854,
        not_understood_data_catalog_count: 246,
        completion_rate: 78,
    },
    {
        department_name: '项目管理部',
        understood_data_catalog_count: 743,
        not_understood_data_catalog_count: 257,
        completion_rate: 74,
    },
    {
        department_name: '架构设计部',
        understood_data_catalog_count: 632,
        not_understood_data_catalog_count: 268,
        completion_rate: 70,
    },
    {
        department_name: '数据库管理部',
        understood_data_catalog_count: 521,
        not_understood_data_catalog_count: 279,
        completion_rate: 65,
    },
    {
        department_name: '网络工程部',
        understood_data_catalog_count: 410,
        not_understood_data_catalog_count: 290,
        completion_rate: 59,
    },
    {
        department_name: '安全防护部',
        understood_data_catalog_count: 299,
        not_understood_data_catalog_count: 301,
        completion_rate: 50,
    },
    {
        department_name: '监控运维部',
        understood_data_catalog_count: 188,
        not_understood_data_catalog_count: 312,
        completion_rate: 38,
    },
    {
        department_name: '性能优化部',
        understood_data_catalog_count: 177,
        not_understood_data_catalog_count: 323,
        completion_rate: 35,
    },
    {
        department_name: '容灾备份部',
        understood_data_catalog_count: 166,
        not_understood_data_catalog_count: 334,
        completion_rate: 33,
    },
]

export const understandTaskDetailDataMock = {
    total_task_count: 100,
    completed_task_count: 80,
    in_progress_task_count: 20,
    abnormal_task_count: 10,
}

export const understandCatalogDetailDataMock = [
    {
        name: '目录1',
        resource: [
            { resource_type: 1, resource_count: 41 },
            { resource_type: 2, resource_count: 31 },
            { resource_type: 3, resource_count: 21 },
        ],
        resource_count: 93,
        // 毫秒数
        updated_at: 1715856000000,
        department: '部门1',
        sync_mechanism: 0,
        completeness_score: 71,
        accuracy_score: 76,
        timeliness_score: 81,
    },
    {
        name: '目录2',
        resource: [
            { resource_type: 1, resource_count: 42 },
            { resource_type: 2, resource_count: 32 },
            { resource_type: 3, resource_count: 22 },
        ],
        resource_count: 96,
        updated_at: 1715942400000,
        department: '部门2',
        sync_mechanism: 1,
        completeness_score: 72,
        accuracy_score: 77,
        timeliness_score: 82,
    },
    {
        name: '目录3',
        resource: [
            { resource_type: 1, resource_count: 43 },
            { resource_type: 2, resource_count: 33 },
            { resource_type: 3, resource_count: 23 },
        ],
        resource_count: 99,
        updated_at: 1716028800000,
        department: '部门3',
        sync_mechanism: 2,
        completeness_score: 73,
        accuracy_score: 78,
        timeliness_score: 83,
    },
    {
        name: '目录4',
        resource: [
            { resource_type: 1, resource_count: 44 },
            { resource_type: 2, resource_count: 34 },
            { resource_type: 3, resource_count: 24 },
        ],
        resource_count: 102,
        updated_at: 1716115200000,
        department: '部门4',
        sync_mechanism: 0,
        completeness_score: 74,
        accuracy_score: 79,
        timeliness_score: 84,
    },
    {
        name: '目录5',
        resource: [
            { resource_type: 1, resource_count: 45 },
            { resource_type: 2, resource_count: 35 },
            { resource_type: 3, resource_count: 25 },
        ],
        resource_count: 105,
        updated_at: 1716201600000,
        department: '部门5',
        sync_mechanism: 1,
        completeness_score: 75,
        accuracy_score: 80,
        timeliness_score: 85,
    },
    {
        name: '目录6',
        resource: [
            { resource_type: 1, resource_count: 46 },
            { resource_type: 2, resource_count: 36 },
            { resource_type: 3, resource_count: 26 },
        ],
        resource_count: 108,
        updated_at: 1716288000000,
        department: '部门6',
        sync_mechanism: 2,
        completeness_score: 76,
        accuracy_score: 81,
        timeliness_score: 86,
    },
    {
        name: '目录7',
        resource: [
            { resource_type: 1, resource_count: 47 },
            { resource_type: 2, resource_count: 37 },
            { resource_type: 3, resource_count: 27 },
        ],
        resource_count: 111,
        updated_at: 1716374400000,
        department: '部门7',
        sync_mechanism: 0,
        completeness_score: 77,
        accuracy_score: 82,
        timeliness_score: 87,
    },
    {
        name: '目录8',
        resource: [
            { resource_type: 1, resource_count: 48 },
            { resource_type: 2, resource_count: 38 },
            { resource_type: 3, resource_count: 28 },
        ],
        resource_count: 114,
        updated_at: 1716460800000,
        department: '部门8',
        sync_mechanism: 1,
        completeness_score: 78,
        accuracy_score: 83,
        timeliness_score: 88,
    },
    {
        name: '目录9',
        resource: [
            { resource_type: 1, resource_count: 49 },
            { resource_type: 2, resource_count: 39 },
            { resource_type: 3, resource_count: 29 },
        ],
        resource_count: 117,
        updated_at: 1716547200000,
        department: '部门9',
        sync_mechanism: 2,
        completeness_score: 79,
        accuracy_score: 84,
        timeliness_score: 89,
    },
    {
        name: '目录10',
        resource: [
            { resource_type: 1, resource_count: 50 },
            { resource_type: 2, resource_count: 40 },
            { resource_type: 3, resource_count: 30 },
        ],
        resource_count: 120,
        updated_at: 1716633600000,
        department: '部门10',
        sync_mechanism: 0,
        completeness_score: 80,
        accuracy_score: 85,
        timeliness_score: 95,
    },
    {
        name: '目录11',
        resource: [
            { resource_type: 1, resource_count: 51 },
            { resource_type: 2, resource_count: 41 },
            { resource_type: 3, resource_count: 21 },
        ],
        resource_count: 113,
        updated_at: 1716720000000,
        department: '部门1',
        sync_mechanism: 1,
        completeness_score: 81,
        accuracy_score: 76,
        timeliness_score: 81,
    },
    {
        name: '目录12',
        resource: [
            { resource_type: 1, resource_count: 52 },
            { resource_type: 2, resource_count: 42 },
            { resource_type: 3, resource_count: 22 },
        ],
        resource_count: 116,
        updated_at: 1716806400000,
        department: '部门2',
        sync_mechanism: 2,
        completeness_score: 82,
        accuracy_score: 77,
        timeliness_score: 82,
    },
    {
        name: '目录13',
        resource: [
            { resource_type: 1, resource_count: 53 },
            { resource_type: 2, resource_count: 43 },
            { resource_type: 3, resource_count: 23 },
        ],
        resource_count: 119,
        updated_at: 1716892800000,
        department: '部门3',
        sync_mechanism: 0,
        completeness_score: 83,
        accuracy_score: 78,
        timeliness_score: 83,
    },
    {
        name: '目录14',
        resource: [
            { resource_type: 1, resource_count: 54 },
            { resource_type: 2, resource_count: 44 },
            { resource_type: 3, resource_count: 24 },
        ],
        resource_count: 122,
        updated_at: 1716979200000,
        department: '部门4',
        sync_mechanism: 1,
        completeness_score: 84,
        accuracy_score: 79,
        timeliness_score: 84,
    },
    {
        name: '目录15',
        resource: [
            { resource_type: 1, resource_count: 55 },
            { resource_type: 2, resource_count: 45 },
            { resource_type: 3, resource_count: 25 },
        ],
        resource_count: 125,
        updated_at: 1717065600000,
        department: '部门5',
        sync_mechanism: 2,
        completeness_score: 85,
        accuracy_score: 80,
        timeliness_score: 85,
    },
    {
        name: '目录16',
        resource: [
            { resource_type: 1, resource_count: 56 },
            { resource_type: 2, resource_count: 46 },
            { resource_type: 3, resource_count: 26 },
        ],
        resource_count: 128,
        updated_at: 1717152000000,
        department: '部门6',
        sync_mechanism: 0,
        completeness_score: 86,
        accuracy_score: 81,
        timeliness_score: 86,
    },
    {
        name: '目录17',
        resource: [
            { resource_type: 1, resource_count: 57 },
            { resource_type: 2, resource_count: 47 },
            { resource_type: 3, resource_count: 27 },
        ],
        resource_count: 131,
        updated_at: 1717238400000,
        department: '部门7',
        sync_mechanism: 1,
        completeness_score: 87,
        accuracy_score: 82,
        timeliness_score: 87,
    },
    {
        name: '目录18',
        resource: [
            { resource_type: 1, resource_count: 58 },
            { resource_type: 2, resource_count: 48 },
            { resource_type: 3, resource_count: 28 },
        ],
        resource_count: 134,
        updated_at: 1717324800000,
        department: '部门8',
        sync_mechanism: 2,
        completeness_score: 88,
        accuracy_score: 83,
        timeliness_score: 88,
    },
    {
        name: '目录19',
        resource: [
            { resource_type: 1, resource_count: 59 },
            { resource_type: 2, resource_count: 44 },
            { resource_type: 3, resource_count: 29 },
        ],
        resource_count: 132,
        updated_at: 1717411200000,
        department: '部门9',
        sync_mechanism: 0,
        completeness_score: 89,
        accuracy_score: 84,
        timeliness_score: 89,
    },
    {
        name: '目录20',
        resource: [
            { resource_type: 1, resource_count: 60 },
            { resource_type: 2, resource_count: 45 },
            { resource_type: 3, resource_count: 20 },
        ],
        resource_count: 125,
        updated_at: 1717497600000,
        department: '部门10',
        sync_mechanism: 1,
        completeness_score: 90,
        accuracy_score: 85,
        timeliness_score: 80,
    },
    {
        name: '目录21',
        resource: [
            { resource_type: 1, resource_count: 61 },
            { resource_type: 2, resource_count: 31 },
            { resource_type: 3, resource_count: 21 },
        ],
        resource_count: 113,
        updated_at: 1717584000000,
        department: '部门1',
        sync_mechanism: 2,
        completeness_score: 91,
        accuracy_score: 76,
        timeliness_score: 81,
    },
    {
        name: '目录22',
        resource: [
            { resource_type: 1, resource_count: 62 },
            { resource_type: 2, resource_count: 32 },
            { resource_type: 3, resource_count: 22 },
        ],
        resource_count: 116,
        updated_at: 1717670400000,
        department: '部门2',
        sync_mechanism: 0,
        completeness_score: 92,
        accuracy_score: 77,
        timeliness_score: 82,
    },
    {
        name: '目录23',
        resource: [
            { resource_type: 1, resource_count: 63 },
            { resource_type: 2, resource_count: 33 },
            { resource_type: 3, resource_count: 23 },
        ],
        resource_count: 119,
        updated_at: 1717756800000,
        department: '部门3',
        sync_mechanism: 1,
        completeness_score: 93,
        accuracy_score: 78,
        timeliness_score: 83,
    },
    {
        name: '目录24',
        resource: [
            { resource_type: 1, resource_count: 64 },
            { resource_type: 2, resource_count: 34 },
            { resource_type: 3, resource_count: 24 },
        ],
        resource_count: 122,
        updated_at: 1717843200000,
        department: '部门4',
        sync_mechanism: 2,
        completeness_score: 94,
        accuracy_score: 79,
        timeliness_score: 84,
    },
    {
        name: '目录25',
        resource: [
            { resource_type: 1, resource_count: 65 },
            { resource_type: 2, resource_count: 35 },
            { resource_type: 3, resource_count: 25 },
        ],
        resource_count: 125,
        updated_at: 1717929600000,
        department: '部门5',
        sync_mechanism: 0,
        completeness_score: 95,
        accuracy_score: 80,
        timeliness_score: 85,
    },
    {
        name: '目录26',
        resource: [
            { resource_type: 1, resource_count: 66 },
            { resource_type: 2, resource_count: 36 },
            { resource_type: 3, resource_count: 26 },
        ],
        resource_count: 128,
        updated_at: 1718016000000,
        department: '部门6',
        sync_mechanism: 1,
        completeness_score: 96,
        accuracy_score: 81,
        timeliness_score: 86,
    },
    {
        name: '目录27',
        resource: [
            { resource_type: 1, resource_count: 67 },
            { resource_type: 2, resource_count: 37 },
            { resource_type: 3, resource_count: 27 },
        ],
        resource_count: 131,
        updated_at: 1718102400000,
        department: '部门7',
        sync_mechanism: 2,
        completeness_score: 97,
        accuracy_score: 82,
        timeliness_score: 87,
    },
    {
        name: '目录28',
        resource: [
            { resource_type: 1, resource_count: 68 },
            { resource_type: 2, resource_count: 38 },
            { resource_type: 3, resource_count: 28 },
        ],
        resource_count: 134,
        updated_at: 1718188800000,
        department: '部门8',
        sync_mechanism: 0,
        completeness_score: 98,
        accuracy_score: 83,
        timeliness_score: 88,
    },
    {
        name: '目录29',
        resource: [
            { resource_type: 1, resource_count: 69 },
            { resource_type: 2, resource_count: 39 },
            { resource_type: 3, resource_count: 29 },
        ],
        resource_count: 137,
        updated_at: 1718275200000,
        department: '部门9',
        sync_mechanism: 1,
        completeness_score: 90,
        accuracy_score: 84,
        timeliness_score: 89,
    },
    {
        name: '目录30',
        resource: [
            { resource_type: 1, resource_count: 50 },
            { resource_type: 2, resource_count: 30 },
            { resource_type: 3, resource_count: 20 },
        ],
        resource_count: 100,
        updated_at: 1718361600000,
        department: '部门10',
        sync_mechanism: 2,
        completeness_score: 79,
        accuracy_score: 85,
        timeliness_score: 80,
    },
]
